services:
  main_db:
    image: postgres:15.1
    ports: 
      - '5432:5432'
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=main

  test_db:
    image: postgres:15.1
    ports:
      - '5433:5432'
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=user_test
      - POSTGRES_PASSWORD=password_test
      - POSTGRES_DB=test
  
  cache:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - ./cache:/data
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379

volumes:
  redis:
    driver: local